# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: 主页
    url:
    weight: 10
  - name: 成员
    url: people
    weight: 20
  - name: 课程
    url: courses
    weight: 30
  - name: 数据集
    url: post
    weight: 40
#  - name: 科研项目
#    url: project
#    weight: 50
  - name: 论文成果
    url: publication
    weight: 60
  - name: 联系我们
    url: contact
    weight: 70
